language: php
php:
- 5.3
- 5.4
- 5.5
- hhvm
env:
- WP_VERSION=latest WP_MULTISITE=0
- WP_VERSION=4.1 WP_MULTISITE=0
before_script:
- phpenv local 5.5
- composer install --dev --no-interaction
- phpenv local --unset
- npm install
- bash bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION
script:
- bash bin/phpcs.sh
- phpunit
notifications:
  slack:
    secure: IlB9x2fB9MBssngSWcrnXqxTrGdGrowQUeNZp/NMLOJMry2baxFzVCHqTRNPFuscpp7lLrjqDb5zJVenfd6zJWZ7HIPeXKiVs2VLdL1isD33RY2y8qIFSoKtgxh07TYAHscaDEXKiXCUgNPe1Y0met9VlnGZl9dBg48j3Yce5f752oW05eC5Cg1xj5Wrd3x/PxLzKh08eooyBxnWNS+U2xv1cvchswuwyyv/RsVhig9kYc/pAGIOBZ7DJdnJgOyvRRNHMIdZGqCWhSDqdCCeVcJYuNheUSnmh/jE4CtaN776/lLV+Fjdk985h3IiPWTLsiyiYPW1bIylMGGauVQoubCxrG3nGljzXRpjotrLkd2KZ7ejty0dVPPLO7AjVp+0vdwgnd2NdnFSxwQ2PdTaCFiTmcKrzvz5YZZQHLP/ZNtm9B14+w5VoX7qMMiD12x+eN7l/mP1qwL+YTLukchI8X6uN8la02a3cS1zXMZCbueCPn1rVE5artUCiflSFREAqABaKWxQbWr2506+xHxUKIrfw8u19RHDEKBD1qGE3cJ8qT0HM4ZefrJObOSB3kdo2ODtJf1dfT0P2pL5udCaSg5fsksIfiTG0laHpbSl7iBKP5niMTu+xtExzl+ybsInRf9XQXm0j19N+VuGjEJYtcYA6e30YS1EJC8Xq6JV4UQ=
