language: php
php:
- 5.3
- 5.4
- 5.5
- hhvm
env:
- WP_VERSION=latest WP_MULTISITE=0
- WP_VERSION=4.1 WP_MULTISITE=0
before_script:
- phpenv local 5.5
- composer install --dev --no-interaction
- phpenv local --unset
- npm install
- bash bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION
script:
- bash bin/phpcs.sh
- phpunit
notifications:
  slack:
    secure: WE2lzQOhuc6dNnXCR4iQiC1uHPmXmAuKRxqO8Phlx+XpQJryB01WeqosNVHPKeCTm0AwLQBUs0+CrMfuX0/AaTB10RRpLkZ4CwzMXo/ljUPO9NvLeCNKIR3TCQv/WUyEcxuibHFr58p02O/yzk8m/qE/wUSTjbFiKfSHqGsA82W8uonPJgXqYDq7U6MiXTY+W9+Y1fSvp+GANEOjLFu63uOrHaWfFyGk0P9im9TqDbX+HAxFOfBKQUDueUdDPTF+YdJRKQvz/6pVPWPHcvGPsfLEOzhAvQ/cjAKTDmvU7Qc4LVt/ThvAxGOkJzpBGyUUSO+3AG74b11LmMBu1OFPhVYKNsUH+ykBQNDk8MPU0EfAynxVrFiLplyI2ShuI5ONTTSEwJkHyuZ98sG+gGjndp0i4dpVDZuCaecn3kU77uOBYF2Mp37K8lzDkoA/2Snj/0821M5Ifud/kZJpughiiCy6zmG1TjZMrfu8fmSzTJFJ0NdlgeK/Pxat+X/NyG93EEnWRMt/2lckPFYccXkEKXcKjUnQwgEDAMaPMaeI8ClnWEZJmewGngJ3mLWchuYbiQ/wPGbRVspACj1PMqGL1dzoYpNfXuIG+sSSyxn+WAN5k7glh5jnmJyJhBMOIP/We2s4yaAVMhqJqQi1XfOM764qD2NimdfWw8bhz6zvy/0=
