language: php
php:
- 5.3
- 5.4
- 5.5
- hhvm
env:
- WP_VERSION=latest WP_MULTISITE=0
- WP_VERSION=4.1 WP_MULTISITE=0
before_script:
- phpenv local 5.5
- composer install --dev --no-interaction
- phpenv local --unset
- npm install
- bash bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION
script:
- bash bin/phpcs.sh
- phpunit
notifications:
  slack:
    secure: "s7jjhtGZ/lTpTPsYdcYcqvcTpH/98Fp+M0Z5DygpgFbQpEfYgTkcKTm8ENCl5I23cECDdgZiyMqzcnV3VkFQqG35zfE0XQI7MAAKRgEE9QIoxC4IvumhYOPB3gDx/iQ2YIQbkqAd3KV0tF+c+IvpC27UPuk5A2lIYo9pvD76vyVPU0fxqEAxg/5YTG4KKLDKTHNKDiCPRj8vt9WJMGbVURaSISf9MWFsjtvwOGQI8No+bZTILur91/ySVm8z+C1HHmOJKrFe1vWx/r9GYb7//DnU5cuHsF51vKrdCrl97wE1UPjUySYmUgO5IwOxiSQmDzQPd2MZNerz/UvuOQZvnZHMYWe0ltwOQZjl+yUmt7+owsk3toSkwT/VsRUxImjCuAW1YvvkAHg3D7JzzTsKu/qx4aW/EI+q7IAJ5R3H1c4PazvhdMBfx/XGQ5Vgt470kpjWMVXXFqabwelaoWQVuLGSpgzpyx6U1A7Pf0txpDO3L7fTcY/cHM2AFxVnFlEVnpqlx1e+q0bKKJnaKxfubAKHgwhGx2EpAmSO4fLITxBcU6f+/8Nw2jkmz+fZY44lPEyyThhe7ao6CNMOj25of+a6/3m6eLsxcmE1SgVywja59YPilk8tciiveTLoNqID98MJij0QW1bLoaXf4FRcF1KO38HtUINyAX8/SZyboc8="
