language: php
php:
- 5.4
- 5.5
- 5.6
env:
- WP_VERSION=latest WP_MULTISITE=0
- WP_VERSION=4.1 WP_MULTISITE=0
before_script:
- phpenv local 5.5
- composer install --dev --no-interaction
- phpenv local --unset
- npm install
- bash bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION
script:
- bash bin/phpcs.sh
- phpunit
notifications:
  slack:
    secure: opFsuKmvbqY6p1XR8dGk7/sGHD8XQJLbdO8P2m6N0+JX1VKPtj0UelaV3C2WidruplSI92h//xOBIj1V435lw+8B4a4KOJyau5ZNkv1huXp801l6ffDaaWMdWoZjhh9qj3q3taXSGTRpVXCMzfgxMQ0sf6iB29hTE536iKNcRjYpp40/YwJE0FMVYQrcigTTuovLXT49sJMnXpW926YnTey3GLFywpMMOSyDumKaaZSYSHSstsTgoO5Owcmr35M5C4+M0b/9uzJo3KDefqS/TVHuvZVfvA1sBkUP8qlM11Q7uXGd4jjZ+Z0vhZ+zS2Dd+D2utv/DxMOuA9ON4E8A+xeGNi2+zs9JiZR5/b13XuwLtWCj5bxY72+rXXY7JwT33nHkHRobGJSRfJwoCZDIG9afsCljWZyRytJ+NXsnAk+FB0akBFWCK0YAUj+IvCIjXAFLh0kKoRkFePm9stpcuz6yNB20FZPWrDalpK2QMQdOhs3RRLtcOH9+0U0jxQH+xdF3Sd7uG6L4tT9YR9Hks1Bus6jG5Tb/uAkPEWaxLHmiaJy0SriHDKlk2jLJo4OcNvobR/X5AzNEzeqtLJ0Aqur5Xes1vYUH1sw8wEVfvcD8YlAJklYwJDU91EIqqi5bhjYjecZ1tVh2ee+Q4zXuElpmeVLjxE21ps49gPivfwY=
