language: php
php:
- 5.4
- 5.5
- 5.6
env:
- WP_VERSION=latest WP_MULTISITE=0
- WP_VERSION=4.1 WP_MULTISITE=0
before_script:
- phpenv local 5.5
- composer install --dev --no-interaction
- phpenv local --unset
- npm install
- bash bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION
script:
- bash bin/phpcs.sh
- phpunit
notifications:
  slack:
    secure: CZR2dC/9Vi9NAkZFzrrtzA3dGCOrGIt73lMs6ZBs8WEAQmxCGQAo3LYPF+0me3soeqsPeP27l7x9Gjhsd1msso8fFFpOapfh+pEvwmr952C/XqwzBQGYiyGnvccqgJIy1wbcDsJpx96NW8psL2Vm0pKGEe8I11Wa8x9WL94di6jY35uiXu5gmPHz2OzvnF8CJVmq5A4nIJzaWXE+r+KdwrLRrGbpl3rfQgoRntImwa1OjFY1VZXdJiW7dinoLzFR28nrIDIecUJvH+aGFuGhxAh5w9R77yn1V3HzoOz95t3T8CsrIT077YTk0yK0Y7vOWRHwMCFTMgC7YQH6F0E/hy+71JSk3p31wy673MJ5P1LhLoku8h3SUKxDrIkaeEHmaBI705eIAAMYfO2+mKg9mrv3/DPtVC7M444EAEaOQPP/5m1FG5/vHOS30lBefbqq/IwuE3+CabU/DkKJn6lZvmud9WijHTJNaOhaoG/dlZPUiHF4rRPxFkBAdX5h44N+81T5bsHwrh3vw0KVJaiQbSCNENMLD/PH0bKxSUgsHkP8CkIV7H7bD5Gt9JnH1r0xMNSM1WCQHUA5GPS+Kkwmc1Ib16WbP+j/g7Qa9WKb7uRGOJgj2cYB3AzYC6/Li+ZnNBtks9afha702eTtREWbX4JVMk5EPw5Yj+AMmUMJiRs=
